# This playbook defines tasks specific to Fedora

- name: Adding RPM Fusion Free
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    state: present
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Adding RPM Fusion Nonfree
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    state: present
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Installing packages
  become: true
  ansible.builtin.dnf:
    state: latest
    name:
      - btop
      - cmatrix
      - git
      - htop
      - lolcat
      - most
      - ncdu
      - neofetch
      - pv
      - pwgen
      - ranger
      - sloccount
      - tmux
      - toilet
      - vim
      - wireguard-tools
      - zsh
      # TODO separate desktop role from core
      - vlc
      - libreoffice-langpack-fr

- name: Removing packages
  become: true
  ansible.builtin.dnf:
    state: absent
    name:
      - aajohan*
      - akonadi
      - akregator
      - elisa-player
      - espeak-ng
      - gdouros-*
      - google-noto-cjk-fonts
      - google-noto-cjk-fonts-common
      - google-noto-naskh
      - google-noto-naskh*
      - google-noto-sans-arabic*
      - google-noto-sans-armenian*
      - google-noto-sans-canadian
      - google-noto-sans-canadian*
      - google-noto-sans-cherokee*
      - google-noto-sans-cjk*
      - google-noto-sans-ethiopic*
      - google-noto-sans-georgian*
      - google-noto-sans-gurmukhi*
      - google-noto-sans-hebrew*
      - google-noto-sans-lao*
      - google-noto-sans-mono-vf-fonts*
      - google-noto-sans-sinhala*
      - google-noto-sans-thaana*
      - google-noto-serif-vf-fonts*
      - jomolhari-fonts
      - kaddressbook
      - kde-connect
      - kf5-akonadi-contacts
      - kf5-akonadi-server
      - kf5-akonadi-server-mysql
      - kf5-kontacts
      - khmer-os*
      - kio-gdrive
      - kmahjongg
      - kmail
      - kmail-account-wizard
      - kmines
      - kmouth
      - kolourpaint
      - kontact
      - konversation
      - korganizer
      - kpatience
      - krdc
      - krfb
      - lohit-*
      - NetworkManager-config-connectivity-fedora
      - paktype-*-fonts
      - pim-sieve-editor
      - plasma-welcome
      - qt5-qdbusviewer
      - rit-*-fonts
      - sil-*-fonts
      - thai-*-fonts
      - vazirmatn-*-fonts

# Disable automatic dnf cache refresher
- name: Disabling service (dnf-makecache.timer)
  become: yes
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: dnf-makecache.timer

# Disable hibernation
- name: Masking service (hibernate.target)
  become: yes
  ansible.builtin.systemd:
    masked: true
    name: hibernate.target
