# This role defines tasks specific to openSUSE (desktop environment)

- name: Installing packages
  become: true
  package:
    state: present
    name:
      # - audacious
      # - eog
      # - ffmpeg
      - gimp
      - inkscape
      - vlc

      # Hyprland desktop
      - alacritty
      - blueman
      - brightnessctl
      - file-roller
      - fontawesome-fonts
      - gnome-themes-extras
      - gtk2-engine-murrine
      - hypridle
      - hyprland
      - hyprland-guiutils
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprshot
      - hyprsunset
      - libnotify
      - NetworkManager-applet
      - pavucontrol
      # - qt5-qtwayland
      # - qt5ct
      # - qt6-qtwayland
      # - qt6ct
      - rofi
      - SwayNotificationCenter
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - waybar
      # - wiremix
      - wlogout
      - xdg-desktop-portal-hyprland

- name: Removing packages
  become: true
  package:
    state: absent
    name:
      - 7zip
      - unar
