# This role defines tasks specific to Ubuntu (CLI environment)

# Used to know if sudo-rs is installed (to use in become_exe below)
# This is to mitigate an incompatibility between Ansible and sudo-rs
# https://github.com/ansible/ansible/issues/85837
# TODO: remove this mitigation once this bug has been solved
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Installing packages
  become: true
  become_exe: "{{ 'sudo.ws' if ansible_facts.packages['sudo-rs'] is defined else 'sudo' }}"
  ansible.builtin.apt:
    state: present
    name:
      - btop
      - cmatrix
      - fastfetch
      - git
      - htop
      - lolcat
      - most
      - ncdu
      - pv
      - pwgen
      - ranger
      - sloccount
      - tmux
      - toilet
      - zsh

- name: Removing packages
  become: true
  become_exe: "{{ 'sudo.ws' if ansible_facts.packages['sudo-rs'] is defined else 'sudo' }}"
  ansible.builtin.apt:
    state: absent
    name:
      - fonts-beng
      - fonts-beng-extra
      - fonts-deva
      - fonts-deva-extra
      - fonts-gargi
      - fonts-gubbi
      - fonts-gujr
      - fonts-gujr-extra
      - fonts-guru
      - fonts-guru-extra
      - fonts-indic
      - fonts-kacst
      - fonts-kacst-one
      - fonts-kalapi
      - fonts-khmeros-core
      - fonts-knda
      - fonts-lao
      - fonts-lato
      - fonts-lklug-sinhala
      - fonts-lohit*
      - fonts-mlym
      - fonts-nakula
      - fonts-navilu
      - fonts-noto-cjk
      - fonts-orya
      - fonts-orya-extra
      - fonts-pagul
      - fonts-sahadeva
      - fonts-samyak*
      - fonts-sarai
      - fonts-sil-abyssinica
      - fonts-sil-padauk
      - fonts-smc*
      - fonts-taml
      - fonts-telu
      - fonts-telu-extra
      - fonts-teluguvijayam
      - fonts-thai-tlwg
      - fonts-tibetan-machine
      - fonts-tlwg*
      - fonts-yrsa-rasa

- name: Changing shell to zsh
  become: true
  become_exe: "{{ 'sudo.ws' if ansible_facts.packages['sudo-rs'] is defined else 'sudo' }}"
  user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /bin/zsh
