# Holo Night style for Hyprlock

background {
    monitor =
    path = $HOME/.config/mydesktop/current-theme/wallpaper/wallpaper.jpg
    blur_passes = 3
    contrast = 1
    brightness = 0.7
    noise = 0.07,
    vibrancy = 1
    vibrancy_darkness = 0.2,
}

input-field {
    monitor =
    size = 160, 24
    outline_thickness = 1
    dots_size = 0.5 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgba(255, 255, 255, 0.612)
    fade_on_empty = false
    fade_timeout = 500 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = Mot de passe # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = 8 # -1 means complete rounding (circle/oval)
    check_color = rgba(211, 255, 211, 0.6)
    fail_color = rgba(206, 85, 100, 0.6) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 3
    shadow_color = rgba(255, 255, 255, 0.3)
    shadow_boost = 0.9
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$TIME"
    color = rgba(255, 255, 255, 0.5)
    font_size = 55
    font_family = Fira Sans
    position = 0, 300
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 3
    shadow_color = rgba(255, 255, 255, 0.2)
    shadow_boost = 0.9
}

label {
    monitor =
    text = $USER
    color = rgba(255, 255, 255, 0.5)
    font_size = 20
    font_family = Fira Sans
    position = 0, 230
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 3
    shadow_color = rgba(255, 255, 255, 0.2)
    shadow_boost = 0.9
}
