# This role defines tasks specific to Fedora (CLI environment)

- name: Adding RPM Fusion Free
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    state: present
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Adding RPM Fusion Nonfree
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    state: present
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Installing packages
  become: true
  ansible.builtin.dnf:
    state: latest
    name:
      - btop
      - cmatrix
      - git
      - htop
      - lm_sensors
      - lolcat
      - most
      - ncdu
      - neofetch
      - p7zip
      - pv
      - pwgen
      - ranger
      - sloccount
      - tmux
      - toilet
      - vim
      - wireguard-tools
      - zsh

- name: Removing packages
  become: true
  ansible.builtin.dnf:
    state: absent
    name:
      - aajohan*
      - akonadi
      - akregator
      - elisa-player
      - espeak-ng
      - gdouros-*
      - gnome-tour
      - google-noto-cjk-fonts
      - google-noto-cjk-fonts-common
      - google-noto-naskh*
      - google-noto-sans-arabic*
      - google-noto-sans-armenian*
      - google-noto-sans-bengali*
      - google-noto-sans-canadian*
      - google-noto-sans-cherokee*
      - google-noto-sans-cjk*
      - google-noto-sans-devanagari*
      - google-noto-sans-ethiopic*
      - google-noto-sans-georgian*
      - google-noto-sans-gujarati*
      - google-noto-sans-gurmukhi*
      - google-noto-sans-hebrew*
      - google-noto-sans-kannada*
      - google-noto-sans-khmer*
      - google-noto-sans-lao*
      - google-noto-sans-mono-cjk*
      - google-noto-sans-oriya*
      - google-noto-sans-sinhala*
      - google-noto-sans-tamil*
      - google-noto-sans-telugu*
      - google-noto-sans-thaana*
      - google-noto-sans-thai*
      - google-noto-serif-armenian*
      - google-noto-serif-bengali*
      - google-noto-serif-cjk*
      - google-noto-serif-devanagari*
      - google-noto-serif-georgian*
      - google-noto-serif-gujarati*
      - google-noto-serif-gurmukhi*
      - google-noto-serif-hebrew*
      - google-noto-serif-kannada*
      - google-noto-serif-khmer*
      - google-noto-serif-lao*
      - google-noto-serif-oriya*
      - google-noto-serif-sinhala*
      - google-noto-serif-tamil*
      - google-noto-serif-telugu*
      - google-noto-serif-thai*
      - jomolhari-fonts
      - kaddressbook
      - kde-connect
      - kf5-akonadi-contacts
      - kf5-akonadi-server
      - kf5-akonadi-server-mysql
      - kf5-kontacts
      - khmer-os*
      - kio-gdrive
      - kmahjongg
      - kmail
      - kmail-account-wizard
      - kmines
      - kmouth
      - kolourpaint
      - kontact
      - konversation
      - korganizer
      - kpatience
      - krdc
      - krfb
      - lohit-*
      - NetworkManager-config-connectivity-fedora
      - paktype-*-fonts
      - pim-sieve-editor
      - plasma-welcome
      - qt5-qdbusviewer
      - rit-*-fonts
      - sil-*-fonts
      - thai-*-fonts
      - vazirmatn-*-fonts

# Disable automatic dnf cache refresher
- name: Disabling service (dnf-makecache.timer)
  become: yes
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: dnf-makecache.timer

# Disable qemu-guest-agent service
- name: Disabling service (qemu-guest-agent.service)
  become: yes
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: qemu-guest-agent.service

# Disable flatpak-add-fedora-repos service
- name: Disabling service (flatpak-add-fedora-repos.service)
  become: yes
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: flatpak-add-fedora-repos.service

# Disable hibernation
- name: Masking service (hibernate.target)
  become: yes
  ansible.builtin.systemd:
    masked: true
    name: hibernate.target

- name: Changing shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
