background {
    monitor =
    path = $HOME/.config/mydesktop/current-theme/wallpaper/wallpaper.jpg
    blur_passes = 3
    contrast = 1
    brightness = 0.7
    noise = 0.03
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 160, 24
    outline_thickness = 3
    dots_size = 0.5 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(143, 159, 169)
    inner_color = rgba(43, 48, 59, 0.47)
    font_color = rgb(239, 241, 245)
    fade_on_empty = false
    fade_timeout = 500 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = Mot de passe # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = 0 # -1 means complete rounding (circle/oval)
    check_color = rgb(239, 241, 245)
    fail_color = rgb(206, 85, 100) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 1
    shadow_color = rgba(0, 0, 0, 1)
    shadow_boost = 0.3
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$TIME"
    color = rgb(239, 241, 245)
    font_size = 55
    font_family = Fira Semibold
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(239, 241, 245)
    font_size = 20
    font_family = Fira Semibold
    position = 0, 230
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
    shadow_color = rgb(43, 48, 59)
    shadow_boost = 2
}
