# This role defines tasks specific to Ubuntu (desktop environment)

- name: Installing packages
  become: true
  become_exe: "{{ 'sudo.ws' if ansible_facts.packages['sudo-rs'] is defined else 'sudo' }}"
  ansible.builtin.apt:
    state: present
    name:
      - audacious
      - fonts-cantarell
      - fonts-crosextra-carlito
      - gimp
      - inkscape
      - ttf-mscorefonts-installer
      - vlc
      
      # Disabled because it is not well supported on Ubuntu
      # # Hyprland desktop
      # - alacritty
      # - blueman
      # # - fontawesome-fonts-all
      # - gnome-themes-extra
      # - gtk2-engines-murrine
      # - hypridle
      # - hyprland
      # - hyprland-qtutils
      # - hyprlock
      # - hyprpaper
      # - hyprpicker
      # - hyprpolkitagent
      # # - hyprshot
      # # - hyprsunset
      # - libnotify4
      # - network-manager-applet
      # - pavucontrol
      # - rofi
      # - sway-notification-center
      # - thunar
      # - thunar-archive-plugin
      # - waybar
      # # - wiremix
      # - wlogout
      # - xdg-desktop-portal-hyprland
